<h1>Numpy</h1>

In [44]:
import numpy as np
my_array = np.arange(5, 101, 5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [45]:
my_array_multiples_of_10 = my_array[my_array % 10 == 0]
my_array_multiples_of_10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [46]:
my_array_2d = my_array.reshape(-1, 2)
my_array_2d

array([[  5,  10],
       [ 15,  20],
       [ 25,  30],
       [ 35,  40],
       [ 45,  50],
       [ 55,  60],
       [ 65,  70],
       [ 75,  80],
       [ 85,  90],
       [ 95, 100]])

In [47]:
my_second_array = (my_array_multiples_of_10 - 5).reshape(-1, 2) 
my_second_array

array([[ 5, 15],
       [25, 35],
       [45, 55],
       [65, 75],
       [85, 95]])

In [48]:
result_array = np.hstack((my_array_2d.T, my_second_array.T))
result_array

array([[  5,  15,  25,  35,  45,  55,  65,  75,  85,  95,   5,  25,  45,
         65,  85],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100,  15,  35,  55,
         75,  95]])

In [49]:
original_array = result_array.T.copy()
selected_rows = original_array[1:3, :]
divisor = my_array_2d[0, :]
result = selected_rows / divisor
original_array[1:3, :] = result
original_array

array([[  5,  10],
       [  3,   2],
       [  5,   3],
       [ 35,  40],
       [ 45,  50],
       [ 55,  60],
       [ 65,  70],
       [ 75,  80],
       [ 85,  90],
       [ 95, 100],
       [  5,  15],
       [ 25,  35],
       [ 45,  55],
       [ 65,  75],
       [ 85,  95]])

In [50]:
unchanged_mask = (original_array == result_array.T)
unchanged_elements = original_array[unchanged_mask]
# unchanged_elements = np.unique(unchanged_elements)

unchanged_elements

array([  5,  10,  35,  40,  45,  50,  55,  60,  65,  70,  75,  80,  85,
        90,  95, 100,   5,  15,  25,  35,  45,  55,  65,  75,  85,  95])

In [51]:
two_d_array = []
if unchanged_elements.size > 0:
    if unchanged_elements.size % 5 == 0:
        two_d_array = unchanged_elements.reshape(-1, 5)
        if two_d_array.shape[0] >= 3:
            two_d_array[[0, 2]] = two_d_array[[2, 0]]
        else:
            two_d_array = unchanged_elements.reshape(-1, 5)
    else:
        print(f"Не удалось преобразовать в двумерный массив, так как размер {unchanged_elements.size} не кратен 5.")
else:
    two_d_array = np.array([])
two_d_array

Не удалось преобразовать в двумерный массив, так как размер 26 не кратен 5.


[]

In [52]:
mean_per_row = np.mean(original_array, axis=1)
median_per_row = np.median(original_array, axis=1)
std_per_row = np.std(original_array, axis=1)

mean_per_row, median_per_row, std_per_row

(array([ 7.5,  2.5,  4. , 37.5, 47.5, 57.5, 67.5, 77.5, 87.5, 97.5, 10. ,
        30. , 50. , 70. , 90. ]),
 array([ 7.5,  2.5,  4. , 37.5, 47.5, 57.5, 67.5, 77.5, 87.5, 97.5, 10. ,
        30. , 50. , 70. , 90. ]),
 array([2.5, 0.5, 1. , 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 5. , 5. , 5. ,
        5. , 5. ]))

In [53]:
max_per_row = np.max(original_array, axis=1)
normalized_array = original_array / max_per_row[:, np.newaxis]

normalized_array

array([[0.5       , 1.        ],
       [1.        , 0.66666667],
       [1.        , 0.6       ],
       [0.875     , 1.        ],
       [0.9       , 1.        ],
       [0.91666667, 1.        ],
       [0.92857143, 1.        ],
       [0.9375    , 1.        ],
       [0.94444444, 1.        ],
       [0.95      , 1.        ],
       [0.33333333, 1.        ],
       [0.71428571, 1.        ],
       [0.81818182, 1.        ],
       [0.86666667, 1.        ],
       [0.89473684, 1.        ]])

<h1>Pandas</h1>

In [54]:
import pandas as pd

df = pd.read_csv("./data/Global Population Trends(2016-2022).csv")

In [55]:
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8           3  
2                  46.3           3  
3                  44.8           3  
4                  43.4           3

In [56]:
df.shape

(1073, 12)

In [57]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


In [59]:
df1 = df[df['Total Population'] != '-'].copy()
df1['Total Population'] = df1['Total Population'].str.replace(',', '').astype(float)

df1

Country  Year  Total Population Urban Population Rural Population  \
1     Afghanistan  2018        36686784.0        9,353,296       27,333,488   
2     Afghanistan  2019        37769499.0        9,727,157       28,042,342   
3     Afghanistan  2020        38972230.0       10,142,913       28,829,317   
4     Afghanistan  2021        40099462.0       10,551,772       29,547,690   
6         Albania  2018         2866376.0        1,728,969        1,137,407   
...           ...   ...               ...              ...              ...   
1067       Zambia  2021        19473125.0        8,800,295       10,672,830   
1069     Zimbabwe  2018        15052184.0        4,848,158       10,204,026   
1070     Zimbabwe  2019        15354608.0        4,945,719       10,408,889   
1071     Zimbabwe  2020        15669666.0        5,052,214       10,617,452   
1072     Zimbabwe  2021        15993524.0        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

In [60]:
df1.describe()

Year  Total Population  Birth Rate  Death Rate
count   864.000000      8.640000e+02  864.000000  864.000000
mean   2019.500000      3.577942e+07   18.548384    7.889123
std       1.118682      1.393935e+08    9.887518    3.041385
min    2018.000000      1.086500e+04    0.000000    0.000000
25%    2018.750000      7.771928e+05   10.500000    6.116500
50%    2019.500000      6.332328e+06   15.628500    7.453500
75%    2020.250000      2.499417e+07   25.565000    9.385000
max    2021.000000      1.412360e+09   46.127000   21.700000

In [61]:
df_sorted = df1.sort_values(by=['Year', 'Total Population'], ascending=[True, False])
df_sorted.head()

Country  Year  Total Population Urban Population Rural Population  \
202           China  2018      1.402760e+09      829,760,595      572,999,405   
432           India  2018      1.369003e+09      465,871,825      903,131,481   
1019  United States  2018      3.268382e+08      268,844,029       57,994,170   
437       Indonesia  2018      2.670668e+08      147,754,731      119,312,112   
725        Pakistan  2018      2.197315e+08       80,566,744      139,164,735   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
202                 149              78      10.860       7.080   
432                 460              71      17.651       6.644   
1019                 36              79      11.600       8.678   
437                 142              70      17.179       7.496   
725                 285              66      28.594       6.843   

     Fertility Rate Infant Mortality Rate Growth Rate  
202           1.554                   6.4           0  
432           2.177                  29.8           1  
1019           1.73                   5.6           1  
437           2.234                  20.8           1  
725           3.685                  57.4           2

In [62]:
max_population_country = df1.loc[df1['Total Population'].idxmax(), 'Country']
max_population_country

'China'

In [63]:
min_population_country = df1.loc[df1['Total Population'].idxmin(), 'Country']
min_population_country

'Tuvalu'

In [64]:
df1.to_excel("./data/Global_Population_Trends_Cleaned.xlsx", index=False)